// source: proto/sdk.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.quibbble.com.QuibbbleGameNotationAction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('jspb.internal.public_for_gencode');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.quibbble.com.QuibbbleGameNotationAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.quibbble.com.QuibbbleGameNotationAction.repeatedFields_, null);
};
goog.inherits(proto.quibbble.com.QuibbbleGameNotationAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.quibbble.com.QuibbbleGameNotationAction.displayName = 'proto.quibbble.com.QuibbbleGameNotationAction';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.quibbble.com.QuibbbleGameNotationAction.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.toObject = function(opt_includeInstance) {
  return proto.quibbble.com.QuibbbleGameNotationAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.quibbble.com.QuibbbleGameNotationAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.quibbble.com.QuibbbleGameNotationAction.toObject = function(includeInstance, msg) {
  var f, obj = {
team: jspb.Message.getFieldWithDefault(msg, 1, 0),
kind: jspb.Message.getFieldWithDefault(msg, 2, 0),
specList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.quibbble.com.QuibbbleGameNotationAction}
 */
proto.quibbble.com.QuibbbleGameNotationAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.quibbble.com.QuibbbleGameNotationAction;
  return proto.quibbble.com.QuibbbleGameNotationAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.quibbble.com.QuibbbleGameNotationAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.quibbble.com.QuibbbleGameNotationAction}
 */
proto.quibbble.com.QuibbbleGameNotationAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTeam(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setKind(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.addSpec(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.quibbble.com.QuibbbleGameNotationAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.quibbble.com.QuibbbleGameNotationAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.quibbble.com.QuibbbleGameNotationAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeam();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getKind();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getSpecList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional int64 team = 1;
 * @return {number}
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.getTeam = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.quibbble.com.QuibbbleGameNotationAction} returns this
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.setTeam = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 kind = 2;
 * @return {number}
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.getKind = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.quibbble.com.QuibbbleGameNotationAction} returns this
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.setKind = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated string spec = 3;
 * @return {!Array<string>}
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.getSpecList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.quibbble.com.QuibbbleGameNotationAction} returns this
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.setSpecList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.quibbble.com.QuibbbleGameNotationAction} returns this
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.addSpec = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.quibbble.com.QuibbbleGameNotationAction} returns this
 */
proto.quibbble.com.QuibbbleGameNotationAction.prototype.clearSpecList = function() {
  return this.setSpecList([]);
};


