// source: proto/sdk.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.quibbble.com.QuibbbleGameNotation');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('jspb.internal.public_for_gencode');
goog.require('proto.quibbble.com.QuibbbleGameNotationAction');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.quibbble.com.QuibbbleGameNotation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.quibbble.com.QuibbbleGameNotation.repeatedFields_, null);
};
goog.inherits(proto.quibbble.com.QuibbbleGameNotation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.quibbble.com.QuibbbleGameNotation.displayName = 'proto.quibbble.com.QuibbbleGameNotation';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.quibbble.com.QuibbbleGameNotation.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.quibbble.com.QuibbbleGameNotation.prototype.toObject = function(opt_includeInstance) {
  return proto.quibbble.com.QuibbbleGameNotation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.quibbble.com.QuibbbleGameNotation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.quibbble.com.QuibbbleGameNotation.toObject = function(includeInstance, msg) {
  var f, obj = {
tagsMap: (f = msg.getTagsMap()) ? f.toObject(includeInstance, undefined) : [],
actionsList: jspb.Message.toObjectList(msg.getActionsList(),
    proto.quibbble.com.QuibbbleGameNotationAction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.quibbble.com.QuibbbleGameNotation}
 */
proto.quibbble.com.QuibbbleGameNotation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.quibbble.com.QuibbbleGameNotation;
  return proto.quibbble.com.QuibbbleGameNotation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.quibbble.com.QuibbbleGameNotation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.quibbble.com.QuibbbleGameNotation}
 */
proto.quibbble.com.QuibbbleGameNotation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getTagsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readStringRequireUtf8, jspb.BinaryReader.prototype.readStringRequireUtf8, null, "", "");
         });
      break;
    case 2:
      var value = new proto.quibbble.com.QuibbbleGameNotationAction;
      reader.readMessage(value,proto.quibbble.com.QuibbbleGameNotationAction.deserializeBinaryFromReader);
      msg.addActions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.quibbble.com.QuibbbleGameNotation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.quibbble.com.QuibbbleGameNotation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.quibbble.com.QuibbbleGameNotation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.quibbble.com.QuibbbleGameNotation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTagsMap(true);
  if (f && f.getLength() > 0) {
jspb.internal.public_for_gencode.serializeMapToBinary(
    message.getTagsMap(true),
    1,
    writer,
    jspb.BinaryWriter.prototype.writeString,
    jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getActionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.quibbble.com.QuibbbleGameNotationAction.serializeBinaryToWriter
    );
  }
};


/**
 * map<string, string> tags = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.quibbble.com.QuibbbleGameNotation.prototype.getTagsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.quibbble.com.QuibbbleGameNotation} returns this
 */
proto.quibbble.com.QuibbbleGameNotation.prototype.clearTagsMap = function() {
  this.getTagsMap().clear();
  return this;
};


/**
 * repeated QuibbbleGameNotationAction actions = 2;
 * @return {!Array<!proto.quibbble.com.QuibbbleGameNotationAction>}
 */
proto.quibbble.com.QuibbbleGameNotation.prototype.getActionsList = function() {
  return /** @type{!Array<!proto.quibbble.com.QuibbbleGameNotationAction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.quibbble.com.QuibbbleGameNotationAction, 2));
};


/**
 * @param {!Array<!proto.quibbble.com.QuibbbleGameNotationAction>} value
 * @return {!proto.quibbble.com.QuibbbleGameNotation} returns this
*/
proto.quibbble.com.QuibbbleGameNotation.prototype.setActionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.quibbble.com.QuibbbleGameNotationAction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.quibbble.com.QuibbbleGameNotationAction}
 */
proto.quibbble.com.QuibbbleGameNotation.prototype.addActions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.quibbble.com.QuibbbleGameNotationAction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.quibbble.com.QuibbbleGameNotation} returns this
 */
proto.quibbble.com.QuibbbleGameNotation.prototype.clearActionsList = function() {
  return this.setActionsList([]);
};


