# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sdk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sdk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsdk.proto\x12\x0cquibbble.sdk\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\";\n\x0fInitGameRequest\x12(\n\x08snapshot\x18\x01 \x01(\x0b\x32\x16.quibbble.sdk.Snapshot\"5\n\rActionRequest\x12$\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x14.quibbble.sdk.Action\"\x1f\n\x0fSnapshotRequest\x12\x0c\n\x04team\x18\x01 \x01(\t\"<\n\x10SnapshotResponse\x12(\n\x08snapshot\x18\x01 \x01(\x0b\x32\x16.quibbble.sdk.Snapshot\"V\n\x06\x41\x63tion\x12\x0c\n\x04team\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\'\n\x04spec\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x42\x07\n\x05_spec\"\x84\x02\n\x08Snapshot\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\r\n\x05teams\x18\x02 \x03(\t\x12\x0c\n\x04turn\x18\x03 \x01(\t\x12\x0f\n\x07winners\x18\x04 \x03(\t\x12%\n\x07history\x18\x05 \x03(\x0b\x32\x14.quibbble.sdk.Action\x12\x11\n\x04seed\x18\x06 \x01(\x03H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x07 \x01(\tH\x01\x88\x01\x01\x12%\n\x07\x61\x63tions\x18\x08 \x03(\x0b\x32\x14.quibbble.sdk.Action\x12\'\n\x04spec\x18\t \x01(\x0b\x32\x14.google.protobuf.AnyH\x02\x88\x01\x01\x42\x07\n\x05_seedB\n\n\x08_messageB\x07\n\x05_spec2\xdd\x01\n\x03SDK\x12\x43\n\x08InitGame\x12\x1d.quibbble.sdk.InitGameRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x41\n\x08\x44oAction\x12\x1b.quibbble.sdk.ActionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n\x0bGetSnapshot\x12\x1d.quibbble.sdk.SnapshotRequest\x1a\x1e.quibbble.sdk.SnapshotResponse\"\x00\x42\x07Z\x05./sdkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./sdk'
  _globals['_INITGAMEREQUEST']._serialized_start=83
  _globals['_INITGAMEREQUEST']._serialized_end=142
  _globals['_ACTIONREQUEST']._serialized_start=144
  _globals['_ACTIONREQUEST']._serialized_end=197
  _globals['_SNAPSHOTREQUEST']._serialized_start=199
  _globals['_SNAPSHOTREQUEST']._serialized_end=230
  _globals['_SNAPSHOTRESPONSE']._serialized_start=232
  _globals['_SNAPSHOTRESPONSE']._serialized_end=292
  _globals['_ACTION']._serialized_start=294
  _globals['_ACTION']._serialized_end=380
  _globals['_SNAPSHOT']._serialized_start=383
  _globals['_SNAPSHOT']._serialized_end=643
  _globals['_SDK']._serialized_start=646
  _globals['_SDK']._serialized_end=867
# @@protoc_insertion_point(module_scope)
