# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import sdk_pb2 as sdk__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sdk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SDKStub(object):
    """gRPC definition for the SDK Server.
    This SDK service should be implemented by developers
    looking to create their own game(s).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitGame = channel.unary_unary(
                '/quibbble.sdk.SDK/InitGame',
                request_serializer=sdk__pb2.InitGameRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DoAction = channel.unary_unary(
                '/quibbble.sdk.SDK/DoAction',
                request_serializer=sdk__pb2.ActionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/quibbble.sdk.SDK/GetSnapshot',
                request_serializer=sdk__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=sdk__pb2.SnapshotResponse.FromString,
                _registered_method=True)


class SDKServicer(object):
    """gRPC definition for the SDK Server.
    This SDK service should be implemented by developers
    looking to create their own game(s).
    """

    def InitGame(self, request, context):
        """Initialize the game.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoAction(self, request, context):
        """Perform an action on the game.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Retrieve the current game snapshot from a specific team's point of view.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDKServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitGame': grpc.unary_unary_rpc_method_handler(
                    servicer.InitGame,
                    request_deserializer=sdk__pb2.InitGameRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DoAction': grpc.unary_unary_rpc_method_handler(
                    servicer.DoAction,
                    request_deserializer=sdk__pb2.ActionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=sdk__pb2.SnapshotRequest.FromString,
                    response_serializer=sdk__pb2.SnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quibbble.sdk.SDK', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quibbble.sdk.SDK', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SDK(object):
    """gRPC definition for the SDK Server.
    This SDK service should be implemented by developers
    looking to create their own game(s).
    """

    @staticmethod
    def InitGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quibbble.sdk.SDK/InitGame',
            sdk__pb2.InitGameRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quibbble.sdk.SDK/DoAction',
            sdk__pb2.ActionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quibbble.sdk.SDK/GetSnapshot',
            sdk__pb2.SnapshotRequest.SerializeToString,
            sdk__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
