# Default values for quibbble-controller

replicaCount: 1

allowOrigins:
- "http://127.0.0.1:8080"

# controller parameters
controller:
  image:
    repository: quibbble/controller
    tag: latest
    pullPolicy: Always
  port: 8080

# watcher parameters
watcher:
  image:
    repository: quibbble/watcher
    tag: latest
    pullPolicy: Always
  suspend: false
  schedule: "*/30 * * * *"

# server parameters
server:
  image:
    repository: quibbble/server
    tag: latest
    pullPolicy: Always

# storage parameters
# if enabled, uncomment lines below. A K8s secret holding
# the storage password will also need to be create before
# installing this chart.
storage:
  enabled: false
  # host: ""
  # username: ""
  # database: ""
  # sslmode: ""

# ingress parameters
ingress:
  host: ""
  port: 80
