# Default values for quibbble-controller

replicaCount: 1

allowOrigins: []

# controller parameters
controller:
  image:
    repository: docker.io/quibbble/controller
    tag: latest
    pullPolicy: IfNotPresent
  port: 8080

# watcher parameters
watcher:
  image:
    repository: docker.io/quibbble/watcher
    tag: latest
    pullPolicy: IfNotPresent
  suspend: false
  schedule: "*/30 * * * *"

# server parameters
server:
  image:
    repository: docker.io/quibbble/server
    tag: latest
    pullPolicy: IfNotPresent

# storage parameters
# if enabled, uncomment lines below. A K8s secret holding
# the storage password will also need to be create before
# installing this chart.
storage:
  enabled: false
  # host: ""
  # username: ""
  # database: ""
  # sslmode: ""

# auth parameters
# if enabled then a K8s secret holding
# the auth key will also need to be create before
# installing this chart.
auth:
  enabled: false

# ingress parameters
ingress:
  host: ""
  port: 80
