# Default values for quibbble-controller

replicaCount: 1

allowOrigins:
- "http://127.0.0.1:8080"

# This secret is created for you if no 'controllerSecretName' is specified:
# 
#  apiVersion: v1
#  kind: Secret
#  data:
#    admin-password: <base64_encoded admin password>
#    storage-password: <base64_encoded storage password>
#  type: Opaque
controllerSecretName: ~
adminPassword: ~

# controller parameters
controller:
  image:
    repository: quibbble/controller
    tag: latest
    pullPolicy: Always
  port: 8080

# watcher parameters
watcher:
  image:
    repository: quibbble/watcher
    tag: latest
    pullPolicy: Always
  suspend: false
  schedule: "*/30 * * * *"

# server parameters
server:
  image:
    repository: quibbble/server
    tag: latest
    pullPolicy: Always

# storage parameters
storage:
  enabled: false
  host: ~
  username: postgres
  password: postgres
  database: postgres
  sslmode: disable

# ingress parameters
ingress:
  host: ~
  port: 80
