# Default values for quibbble-controller

replicaCount: 1

controller:
  image:
    repository: docker.io/quibbble/controller
    tag: latest
    pullPolicy: IfNotPresent
  port: 8080

watcher:
  image:
    repository: docker.io/quibbble/watcher
    tag: latest
    pullPolicy: IfNotPresent
  suspend: false
  schedule: "*/30 * * * *"

ingress:
  host: apiv2.quibbble.com
  port: 80
