# Default values for quibbble-controller

replicaCount: 1

# controller parameters
controller:
  port: 8080
  image:
    repository: quibbble/controller
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: {}
    path: /
    pathType: ImplementationSpecific
    hosts: []
    # - name: ""
    #   tls:
    #     enabled: false
    #     secretName: ""
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []

# watcher parameters
watcher:
  image:
    repository: quibbble/watcher
    tag: latest
    pullPolicy: Always
  suspend: false
  schedule: "*/30 * * * *"
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []

# server parameters
server:
  image:
    repository: quibbble/server
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: {}
    # ingress path follows pattern: '<pathPrefix>/<gameKey>/<gameID><pathPostfix>'
    pathPrefix: ""
    pathPostfix: ""
    pathType: ImplementationSpecific
    hosts: []
    # - name: ""
    #   tls:
    #     enabled: false
    #     secretName: ""
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []

# This secret is created for you if no 'controllerSecretName' is specified.
# Otherwise create a secret with these same data parameters and use it by
# setting the 'controllerSecretName' field with the name of the secret.
# 
# kind: Secret
# apiVersion: v1
# metadata:
#   name: quibbble-controller
# type: Opaque
# data:
#   admin-password: <base64_encoded admin password>
#   storage-password: <base64_encoded storage password>

controllerSecretName: ~
admin:
  username: quibbble
  password: ~

# storage parameters
storage:
  enabled: false
  host: ~
  username: postgres
  password: ~
  database: postgres
  sslmode: disable
