// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: sdk.proto

package sdk

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	game "github.com/quibbble/quibbble-controller/pkg/game"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Player is someone playing the game.
type Player struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique id of the player.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The display name of the player.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The team the player is on.
	Team string `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	// Whether or not the player is currently connected.
	Online        bool `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_sdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *Player) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// Snapshot is a snapshot of the SDK server.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the game was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// List of all players that have ever joined the game.
	Players []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	// The current game snapshot.
	Snapshot *game.Snapshot `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// The list of all past actions done on the game.
	History       []*Action `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_sdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Snapshot) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Snapshot) GetSnapshot() *game.Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Snapshot) GetHistory() []*Action {
	if x != nil {
		return x.History
	}
	return nil
}

// Action is an action done by a player.
type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The player doing the action.
	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	// The action being done on the game.
	Action        *game.Action `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_sdk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *Action) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *Action) GetAction() *game.Action {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_sdk_proto protoreflect.FileDescriptor

const file_sdk_proto_rawDesc = "" +
	"\n" +
	"\tsdk.proto\x12\x10quibbble.com.sdk\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"game.proto\"X\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04team\x18\x03 \x01(\tR\x04team\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\"\xe6\x01\n" +
	"\bSnapshot\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x122\n" +
	"\aplayers\x18\x02 \x03(\v2\x18.quibbble.com.sdk.PlayerR\aplayers\x127\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x1b.quibbble.com.game.SnapshotR\bsnapshot\x122\n" +
	"\ahistory\x18\x04 \x03(\v2\x18.quibbble.com.sdk.ActionR\ahistory\"m\n" +
	"\x06Action\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.quibbble.com.sdk.PlayerR\x06player\x121\n" +
	"\x06action\x18\x02 \x01(\v2\x19.quibbble.com.game.ActionR\x06action2\x9d\x03\n" +
	"\x03SDK\x12E\n" +
	"\vGetSnapshot\x12\x18.quibbble.com.sdk.Player\x1a\x1a.quibbble.com.sdk.Snapshot\"\x00\x12J\n" +
	"\x0eStreamSnapshot\x12\x18.quibbble.com.sdk.Player\x1a\x1a.quibbble.com.sdk.Snapshot\"\x000\x01\x12>\n" +
	"\bJoinTeam\x12\x18.quibbble.com.sdk.Player\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\n" +
	"PlayAction\x12\x18.quibbble.com.sdk.Action\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\n" +
	"UndoAction\x12\x18.quibbble.com.sdk.Player\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\tResetGame\x12\x18.quibbble.com.sdk.Player\x1a\x16.google.protobuf.Empty\"\x00B\x06Z\x04/sdkb\x06proto3"

var (
	file_sdk_proto_rawDescOnce sync.Once
	file_sdk_proto_rawDescData []byte
)

func file_sdk_proto_rawDescGZIP() []byte {
	file_sdk_proto_rawDescOnce.Do(func() {
		file_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_proto_rawDesc), len(file_sdk_proto_rawDesc)))
	})
	return file_sdk_proto_rawDescData
}

var file_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sdk_proto_goTypes = []any{
	(*Player)(nil),                // 0: quibbble.com.sdk.Player
	(*Snapshot)(nil),              // 1: quibbble.com.sdk.Snapshot
	(*Action)(nil),                // 2: quibbble.com.sdk.Action
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*game.Snapshot)(nil),         // 4: quibbble.com.game.Snapshot
	(*game.Action)(nil),           // 5: quibbble.com.game.Action
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_sdk_proto_depIdxs = []int32{
	3,  // 0: quibbble.com.sdk.Snapshot.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: quibbble.com.sdk.Snapshot.players:type_name -> quibbble.com.sdk.Player
	4,  // 2: quibbble.com.sdk.Snapshot.snapshot:type_name -> quibbble.com.game.Snapshot
	2,  // 3: quibbble.com.sdk.Snapshot.history:type_name -> quibbble.com.sdk.Action
	0,  // 4: quibbble.com.sdk.Action.player:type_name -> quibbble.com.sdk.Player
	5,  // 5: quibbble.com.sdk.Action.action:type_name -> quibbble.com.game.Action
	0,  // 6: quibbble.com.sdk.SDK.GetSnapshot:input_type -> quibbble.com.sdk.Player
	0,  // 7: quibbble.com.sdk.SDK.StreamSnapshot:input_type -> quibbble.com.sdk.Player
	0,  // 8: quibbble.com.sdk.SDK.JoinTeam:input_type -> quibbble.com.sdk.Player
	2,  // 9: quibbble.com.sdk.SDK.PlayAction:input_type -> quibbble.com.sdk.Action
	0,  // 10: quibbble.com.sdk.SDK.UndoAction:input_type -> quibbble.com.sdk.Player
	0,  // 11: quibbble.com.sdk.SDK.ResetGame:input_type -> quibbble.com.sdk.Player
	1,  // 12: quibbble.com.sdk.SDK.GetSnapshot:output_type -> quibbble.com.sdk.Snapshot
	1,  // 13: quibbble.com.sdk.SDK.StreamSnapshot:output_type -> quibbble.com.sdk.Snapshot
	6,  // 14: quibbble.com.sdk.SDK.JoinTeam:output_type -> google.protobuf.Empty
	6,  // 15: quibbble.com.sdk.SDK.PlayAction:output_type -> google.protobuf.Empty
	6,  // 16: quibbble.com.sdk.SDK.UndoAction:output_type -> google.protobuf.Empty
	6,  // 17: quibbble.com.sdk.SDK.ResetGame:output_type -> google.protobuf.Empty
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sdk_proto_init() }
func file_sdk_proto_init() {
	if File_sdk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_proto_rawDesc), len(file_sdk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_proto_goTypes,
		DependencyIndexes: file_sdk_proto_depIdxs,
		MessageInfos:      file_sdk_proto_msgTypes,
	}.Build()
	File_sdk_proto = out.File
	file_sdk_proto_goTypes = nil
	file_sdk_proto_depIdxs = nil
}
