// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/sdk.proto

package sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitGameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The initial state of the game.
	Snapshot      *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGameRequest) Reset() {
	*x = InitGameRequest{}
	mi := &file_proto_sdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGameRequest) ProtoMessage() {}

func (x *InitGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGameRequest.ProtoReflect.Descriptor instead.
func (*InitGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *InitGameRequest) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The action to perform on the game.
	Action        *Action `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_proto_sdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *ActionRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team requesting the snapshot.
	Team          string `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_proto_sdk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotRequest) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

type SnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current state of the game.
	Snapshot      *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_proto_sdk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team performing the action.
	Team string `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	// The kind of action to perform.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Any additional information needed to perform the action.
	Spec          *anypb.Any `protobuf:"bytes,3,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_sdk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *Action) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *Action) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Action) GetSpec() *anypb.Any {
	if x != nil {
		return x.Spec
	}
	return nil
}

type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kind of game i.e. tictactoe, chess, etc.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The list of all teams playing the game. The first team in the list should always go first.
	Teams []string `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
	// The team who is currently active.
	Turn string `protobuf:"bytes,3,opt,name=turn,proto3" json:"turn,omitempty"`
	// The list of teams that have won the game.
	Winners []string `protobuf:"bytes,4,rep,name=winners,proto3" json:"winners,omitempty"`
	// The list of all past actions played to reach this current state.
	History []*Action `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`
	// A seed used to generate any deterministic randomness in the game.
	Seed *int64 `protobuf:"varint,6,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	// Human readable message describing what action(s) to take next.
	Message *string `protobuf:"bytes,7,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// The list of all possible actions a team can currently take.
	Actions []*Action `protobuf:"bytes,8,rep,name=actions,proto3" json:"actions,omitempty"`
	// Any additional information about the state of the game i.e. board, decks, hands, etc.
	Spec          *anypb.Any `protobuf:"bytes,9,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_sdk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{5}
}

func (x *Snapshot) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Snapshot) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *Snapshot) GetTurn() string {
	if x != nil {
		return x.Turn
	}
	return ""
}

func (x *Snapshot) GetWinners() []string {
	if x != nil {
		return x.Winners
	}
	return nil
}

func (x *Snapshot) GetHistory() []*Action {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Snapshot) GetSeed() int64 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *Snapshot) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Snapshot) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Snapshot) GetSpec() *anypb.Any {
	if x != nil {
		return x.Spec
	}
	return nil
}

var File_proto_sdk_proto protoreflect.FileDescriptor

const file_proto_sdk_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/sdk.proto\x12\fquibbble.com\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x0fInitGameRequest\x122\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.quibbble.com.SnapshotR\bsnapshot\"=\n" +
	"\rActionRequest\x12,\n" +
	"\x06action\x18\x01 \x01(\v2\x14.quibbble.com.ActionR\x06action\"%\n" +
	"\x0fSnapshotRequest\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team\"F\n" +
	"\x10SnapshotResponse\x122\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.quibbble.com.SnapshotR\bsnapshot\"h\n" +
	"\x06Action\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12-\n" +
	"\x04spec\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\x04spec\x88\x01\x01B\a\n" +
	"\x05_spec\"\xc7\x02\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05teams\x18\x02 \x03(\tR\x05teams\x12\x12\n" +
	"\x04turn\x18\x03 \x01(\tR\x04turn\x12\x18\n" +
	"\awinners\x18\x04 \x03(\tR\awinners\x12.\n" +
	"\ahistory\x18\x05 \x03(\v2\x14.quibbble.com.ActionR\ahistory\x12\x17\n" +
	"\x04seed\x18\x06 \x01(\x03H\x00R\x04seed\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\a \x01(\tH\x01R\amessage\x88\x01\x01\x12.\n" +
	"\aactions\x18\b \x03(\v2\x14.quibbble.com.ActionR\aactions\x12-\n" +
	"\x04spec\x18\t \x01(\v2\x14.google.protobuf.AnyH\x02R\x04spec\x88\x01\x01B\a\n" +
	"\x05_seedB\n" +
	"\n" +
	"\b_messageB\a\n" +
	"\x05_spec2\xdd\x01\n" +
	"\x03SDK\x12C\n" +
	"\bInitGame\x12\x1d.quibbble.com.InitGameRequest\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\bDoAction\x12\x1b.quibbble.com.ActionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\vGetSnapshot\x12\x1d.quibbble.com.SnapshotRequest\x1a\x1e.quibbble.com.SnapshotResponse\"\x00B\aZ\x05./sdkb\x06proto3"

var (
	file_proto_sdk_proto_rawDescOnce sync.Once
	file_proto_sdk_proto_rawDescData []byte
)

func file_proto_sdk_proto_rawDescGZIP() []byte {
	file_proto_sdk_proto_rawDescOnce.Do(func() {
		file_proto_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sdk_proto_rawDesc), len(file_proto_sdk_proto_rawDesc)))
	})
	return file_proto_sdk_proto_rawDescData
}

var file_proto_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_sdk_proto_goTypes = []any{
	(*InitGameRequest)(nil),  // 0: quibbble.com.InitGameRequest
	(*ActionRequest)(nil),    // 1: quibbble.com.ActionRequest
	(*SnapshotRequest)(nil),  // 2: quibbble.com.SnapshotRequest
	(*SnapshotResponse)(nil), // 3: quibbble.com.SnapshotResponse
	(*Action)(nil),           // 4: quibbble.com.Action
	(*Snapshot)(nil),         // 5: quibbble.com.Snapshot
	(*anypb.Any)(nil),        // 6: google.protobuf.Any
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_proto_sdk_proto_depIdxs = []int32{
	5,  // 0: quibbble.com.InitGameRequest.snapshot:type_name -> quibbble.com.Snapshot
	4,  // 1: quibbble.com.ActionRequest.action:type_name -> quibbble.com.Action
	5,  // 2: quibbble.com.SnapshotResponse.snapshot:type_name -> quibbble.com.Snapshot
	6,  // 3: quibbble.com.Action.spec:type_name -> google.protobuf.Any
	4,  // 4: quibbble.com.Snapshot.history:type_name -> quibbble.com.Action
	4,  // 5: quibbble.com.Snapshot.actions:type_name -> quibbble.com.Action
	6,  // 6: quibbble.com.Snapshot.spec:type_name -> google.protobuf.Any
	0,  // 7: quibbble.com.SDK.InitGame:input_type -> quibbble.com.InitGameRequest
	1,  // 8: quibbble.com.SDK.DoAction:input_type -> quibbble.com.ActionRequest
	2,  // 9: quibbble.com.SDK.GetSnapshot:input_type -> quibbble.com.SnapshotRequest
	7,  // 10: quibbble.com.SDK.InitGame:output_type -> google.protobuf.Empty
	7,  // 11: quibbble.com.SDK.DoAction:output_type -> google.protobuf.Empty
	3,  // 12: quibbble.com.SDK.GetSnapshot:output_type -> quibbble.com.SnapshotResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_sdk_proto_init() }
func file_proto_sdk_proto_init() {
	if File_proto_sdk_proto != nil {
		return
	}
	file_proto_sdk_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_sdk_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sdk_proto_rawDesc), len(file_proto_sdk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sdk_proto_goTypes,
		DependencyIndexes: file_proto_sdk_proto_depIdxs,
		MessageInfos:      file_proto_sdk_proto_msgTypes,
	}.Build()
	File_proto_sdk_proto = out.File
	file_proto_sdk_proto_goTypes = nil
	file_proto_sdk_proto_depIdxs = nil
}
