apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
data:
  config.yaml: |
    port: {{ .Values.controller.port }}
    storage:
      enabled: {{ .Values.storage.enabled | default false }}
      host: {{ .Values.storage.host | default "''" }}
      username: {{ .Values.storage.username | default "quibbble" }}
      database: {{ .Values.storage.database | default "quibbble" }}
      sslmode: {{ .Values.storage.sslmode | default "''" }}
    server:
      image:
        repository: {{ .Values.server.image.repository }}
        tag: {{ .Values.server.image.tag }}
        pullPolicy: {{ .Values.server.image.pullPolicy }}
      ingress:
        enabled: {{ .Values.ingress.server.enabled }}
        {{- if .Values.ingress.server.annotations }}
        {{- with .Values.ingress.server.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- else }}
        annotations: {}
        {{- end }}
        pathPrefix: {{ .Values.ingress.server.pathPrefix | default "''" }}
        pathPostfix: {{ .Values.ingress.server.pathPostfix | default "''" }}
        pathType: {{ .Values.ingress.server.pathType | default "ImplementationSpecific" }}
        {{- if .Values.ingress.server.hosts }}
        {{- with .Values.ingress.server.hosts }}
        hosts: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- else }}
        hosts: []
        {{- end }}
        ingressClassName: {{ .Values.ingress.server.ingressClassName | default "''" }}
