apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
data:
  config.yaml: |
    port: {{ .Values.controller.port }}
    storage:
      enabled: {{ .Values.storage.enabled | default false }}
      host: {{ .Values.storage.host | default "" }}
      username: {{ .Values.storage.username | default "" }}
      database: {{ .Values.storage.database | default "" }}
      sslmode: {{ .Values.storage.sslmode | default "" }}
    server:
      image:
        repository: {{ .Values.server.image.repository }}
        tag: {{ .Values.server.image.tag }}
        pullPolicy: {{ .Values.server.image.pullPolicy }}
      ingress:
        enabled: {{ .Values.ingress.server.enabled }}
        {{- if .Values.ingress.server.annotations }}
        {{- with .Values.ingress.server.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- else }}
        annotations: {}
        {{- end }}
        pathPrefix: {{ default .Values.ingress.server.pathPrefix "''" }}
        pathPostfix: {{ default .Values.ingress.server.pathPostfix "''" }}
        pathType: {{ default .Values.ingress.server.pathType "ImplementationSpecific" }}
        {{- if .Values.ingress.server.hosts }}
        {{- with .Values.ingress.server.hosts }}
        hosts: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- else }}
        hosts: []
        {{- end }}
        ingressClassName: {{ default .Values.ingress.server.ingressClassName "''" }}
