apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
data:
  config.yaml: |
    port: {{ .Values.controller.port }}
    storage:
      enabled: {{ .Values.storage.enabled | default false }}
      host: {{ .Values.storage.host | default "''" }}
      username: {{ .Values.storage.username | default "quibbble" }}
      database: {{ .Values.storage.database | default "quibbble" }}
      sslmode: {{ .Values.storage.sslmode | default "''" }}
    server:
      fullname: {{ include "quibbble-controller.fullname" . }}
      namespace: {{ .Release.Namespace }}
      pod:
        image:
          repository: {{ .Values.server.image.repository }}
          tag: {{ .Values.server.image.tag }}
          pullPolicy: {{ .Values.server.image.pullPolicy }}
        admin:
          username: {{ .Values.admin.username }}
          secretName: {{ .Values.controllerSecretName | default (include "quibbble-controller.fullname" .) }}
        resources: {{- toYaml .Values.server.resources | nindent 10 }}
        nodeSelector: {{- toYaml .Values.server.nodeSelector | nindent 10 }}
        affinity: {{- toYaml .Values.server.affinity | nindent 10 }}
        tolerations: {{- toYaml .Values.server.tolerations | nindent 10 }}
      ingress:
        enabled: {{ .Values.server.ingress.enabled }}
        annotations: {{- toYaml .Values.server.ingress.annotations | nindent 10 }}
        pathPrefix: {{ .Values.server.ingress.pathPrefix | default "''" }}
        pathPostfix: {{ .Values.server.ingress.pathPostfix | default "''" }}
        pathType: {{ .Values.server.ingress.pathType | default "ImplementationSpecific" }}
        hosts: {{- toYaml .Values.server.ingress.hosts | nindent 10 }}
        ingressClassName: {{ .Values.server.ingress.ingressClassName | default "''" }}
