apiVersion: batch/v1
kind: CronJob
metadata:
  name: quibbble-watcher
  labels:
    {{- include "quibbble-controller.labels" . | nindent 4 }}
spec:
  suspend: {{ .Values.watcher.suspend }}
  schedule: {{ .Values.watcher.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "quibbble-controller.fullname" . }}
          containers:
          - name: quibbble-watcher
            image: "{{ .Values.watcher.image.repository }}:{{ .Values.watcher.image.tag | default "latest" }}"
            imagePullPolicy: {{ .Values.watcher.image.pullPolicy }}
          restartPolicy: Never
