apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
  labels:
    {{- include "quibbble-controller.labels" . | nindent 4 }}
spec:
  suspend: {{ .Values.cron.suspend }}
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "quibbble-controller.fullname" . }}
          containers:
          - name: {{ include "quibbble-controller.fullname" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: MODE
              value: CLEAN
          restartPolicy: Never
