apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
  labels:
    {{- include "quibbble-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quibbble-controller.selectorLabels" . | nindent 6 }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "quibbble-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "quibbble-controller.fullname" . }}
      containers:
      - name: quibbble-controller
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        env:
        - name: PORT
          value: {{ .Values.controller.port | quote }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.controller.port }}
          initialDelaySeconds: 3
