{{- if .Values.ingress.controller.enabled }}
{{- $fullname := (include "quibbble-controller.fullname" .) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "quibbble-controller.labels" . | nindent 4 }}
  {{- with .Values.ingress.controller.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.controller.ingressClassName }}
  {{- $anyTlsHosts := false -}}
  {{- range .Values.ingress.controller.hosts }}
  {{- if .tls }}
  {{- if .tls.enabled }}
  {{- $anyTlsHosts = true -}}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if $anyTlsHosts }}
  tls:
  {{- range .Values.ingress.controller.hosts }}
  {{- if .tls }}
  {{- if .tls.enabled }}
    - secretName: {{ .tls.secretName }}
      hosts:
        - {{ .name | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.controller.hosts }}
    - host: {{ .name  }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullname }}
                port:
                  number: 80
            {{- if $.Values.ingress.controller.path }}
            path: {{ $.Values.ingress.controller.path }}
            pathType: {{ $.Values.ingress.controller.pathType }}
            {{- end }}
  {{- end }}
{{- end }}
