apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
  labels:
    {{- include "quibbble-controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: [networking.k8s.io]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
  labels:
    {{- include "quibbble-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "quibbble-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "quibbble-controller.fullname" . }}
