apiVersion: v1
kind: Service
metadata:
  name: {{ include "quibbble-controller.fullname" . }}
  labels:
    {{- include "quibbble-controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "quibbble-controller.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.controller.port }}
