// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: game.proto

package quibbble

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GameAction defines a move someone can make that modifies the game state.
type GameAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team doing the action.
	Team string `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	// The kind of action to perform.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Any additional information needed to do the action.
	Spec          *anypb.Any `protobuf:"bytes,3,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAction) Reset() {
	*x = GameAction{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAction) ProtoMessage() {}

func (x *GameAction) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAction.ProtoReflect.Descriptor instead.
func (*GameAction) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameAction) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *GameAction) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GameAction) GetSpec() *anypb.Any {
	if x != nil {
		return x.Spec
	}
	return nil
}

// GameSnapshot defines the game state at a specific point in time.
type GameSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A seed used to generate deterministic randomness in the game.
	Seed int64 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	// The list of all teams playing the game.
	Teams []string `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
	// The team who is currently active.
	Turn string `protobuf:"bytes,3,opt,name=turn,proto3" json:"turn,omitempty"`
	// The list of teams that have won the game.
	Winners []string `protobuf:"bytes,4,rep,name=winners,proto3" json:"winners,omitempty"`
	// Any additional information about the state of the game i.e. board, decks, hands, etc.
	Spec          *anypb.Any `protobuf:"bytes,5,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSnapshot) Reset() {
	*x = GameSnapshot{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSnapshot) ProtoMessage() {}

func (x *GameSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSnapshot.ProtoReflect.Descriptor instead.
func (*GameSnapshot) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameSnapshot) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *GameSnapshot) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *GameSnapshot) GetTurn() string {
	if x != nil {
		return x.Turn
	}
	return ""
}

func (x *GameSnapshot) GetWinners() []string {
	if x != nil {
		return x.Winners
	}
	return nil
}

func (x *GameSnapshot) GetSpec() *anypb.Any {
	if x != nil {
		return x.Spec
	}
	return nil
}

// GameView defines who is looking at the game.
type GameView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team requesting the game snapshot.
	Team          string `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameView) Reset() {
	*x = GameView{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameView) ProtoMessage() {}

func (x *GameView) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameView.ProtoReflect.Descriptor instead.
func (*GameView) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameView) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\fquibbble.com\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"l\n" +
	"\n" +
	"GameAction\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12-\n" +
	"\x04spec\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\x04spec\x88\x01\x01B\a\n" +
	"\x05_spec\"\x9e\x01\n" +
	"\fGameSnapshot\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x03R\x04seed\x12\x14\n" +
	"\x05teams\x18\x02 \x03(\tR\x05teams\x12\x12\n" +
	"\x04turn\x18\x03 \x01(\tR\x04turn\x12\x18\n" +
	"\awinners\x18\x04 \x03(\tR\awinners\x12-\n" +
	"\x04spec\x18\x05 \x01(\v2\x14.google.protobuf.AnyH\x00R\x04spec\x88\x01\x01B\a\n" +
	"\x05_spec\"\x1e\n" +
	"\bGameView\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team2\x89\x02\n" +
	"\x04Game\x12<\n" +
	"\x04Init\x12\x1a.quibbble.com.GameSnapshot\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\x04Load\x12\x1a.quibbble.com.GameSnapshot\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\n" +
	"PlayAction\x12\x18.quibbble.com.GameAction\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\vGetSnapshot\x12\x16.quibbble.com.GameView\x1a\x1a.quibbble.com.GameSnapshot\"\x00B\vZ\t/quibbbleb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_game_proto_goTypes = []any{
	(*GameAction)(nil),    // 0: quibbble.com.GameAction
	(*GameSnapshot)(nil),  // 1: quibbble.com.GameSnapshot
	(*GameView)(nil),      // 2: quibbble.com.GameView
	(*anypb.Any)(nil),     // 3: google.protobuf.Any
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_game_proto_depIdxs = []int32{
	3, // 0: quibbble.com.GameAction.spec:type_name -> google.protobuf.Any
	3, // 1: quibbble.com.GameSnapshot.spec:type_name -> google.protobuf.Any
	1, // 2: quibbble.com.Game.Init:input_type -> quibbble.com.GameSnapshot
	1, // 3: quibbble.com.Game.Load:input_type -> quibbble.com.GameSnapshot
	0, // 4: quibbble.com.Game.PlayAction:input_type -> quibbble.com.GameAction
	2, // 5: quibbble.com.Game.GetSnapshot:input_type -> quibbble.com.GameView
	4, // 6: quibbble.com.Game.Init:output_type -> google.protobuf.Empty
	4, // 7: quibbble.com.Game.Load:output_type -> google.protobuf.Empty
	4, // 8: quibbble.com.Game.PlayAction:output_type -> google.protobuf.Empty
	1, // 9: quibbble.com.Game.GetSnapshot:output_type -> quibbble.com.GameSnapshot
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[0].OneofWrappers = []any{}
	file_game_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
